### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by abenrob** [neocarto/geotoolbox#4]
Would like to implements tests. Do you have opinions on how you would like that to be implemented? 

I think using jest and adding a unit test for each function in `src/gis|helpers|properties` would be reasonable, but I'm open to alternatives.

**Comment by neocarto** [comment]
Be my guest. That's a very good idea. I don't have any particular idea about it. Please suggest a PR.

**Comment by abenrob** [comment]
- [ ] `gis` dir modules
- [ ] `properties` dir modules

I'll do `properties` next

**Comment by neocarto** [comment]
I'm sorry. geotoolbox is not stable yet. The filter function has changed. The old filter function is now called select. 
See https://observablehq.com/@neocartocnrs/filter-geojson?collection=@neocartocnrs/geotoolbox & https://observablehq.com/@neocartocnrs/handle-properties?collection=@neocartocnrs/geotoolbox
