### ISSUE TITLE
Replace JSON.parse(JSON.stringify()) with spread notation

### ISSUE THREAD

**Issue by abenrob** [neocarto/geotoolbox#7]
`JSON.parse(JSON.stringify(object))` creates a deep copy, but is frowned upon, and can be error prone if not copying specifically JSON data. `{...object}` does a shallow copy, which (I think) would be sufficient for GeoJSON properties, since properties are supposed to be one level deep. Cleaner, shorter.

**Comment by neocarto** [comment]
Okay. Thanks for the advice. I'm going to change that.
